book/urls.py
from django.urls import path#, include
from . import views

app_name = 'book'

urlpatterns = [
    path('',views.BookIndex.as_view(),name='index'),
    path('bookchoice', views.book_python,name='booklist'),
    # path('admin/', admin.site.urls),
    # path('accounts/',include('accounts.urls')),
    # path('accounts/', include('allauth.urls')),
    # path('xray/',include('xray.urls')),

]

deepbook/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('ourteam/', views.TeamPage.as_view(), name='ourteam'),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('xray/', include('xray.urls')),
    path('book/', include('book.urls')),
    # path('accounts/',include('accounts.urls')),
    # path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xray/urls.py
# oauth/posts/urls.py 참고함

from django.conf.urls.static import static
from django.urls import path
from . import views
from django.conf import settings

app_name='xray'

urlpatterns = [
    path('',views.XrayIndex.as_view(),name="index"),
    path('create/', views.XrayCreate.as_view(), name='create'),
    path('list/', views.XrayList.as_view(), name='list'),
    path('<int:pk>/', views.XrayDetail.as_view(), name='detail'),
    path('<int:pk>/delete/', views.XrayDelete.as_view(), name='delete'),
    path('<int:pk>/diagnosis/', views.XrayDiagnosis, name='diagnosis'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models

# Create your models here.

deepbook/models.py
from django.db import models
from django.conf import settings

class Deep(models.Model):
    image = models.ImageField()
    result = models.TextField()
    time = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ['-time']  # 최신글이 가장 위로 올라오도록 역순으로 지정
        

xray/models.py
# oauth/posts/models.py 참고

from django.db import models
from django.conf import settings
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


def post_image_path(instance, filename):
    return 'image/{}/{}'.format(instance.pk, filename)

class Xray(models.Model):
    image = ProcessedImageField(
                upload_to=post_image_path,
                processors=[ResizeToFill(300,300)],
                format='JPEG',
                options={'quality':90},
                )
#models.ImageField()
    def get_absolute_url(self):
         return reverse('xray:detail', kwargs={'pk': self.pk})


    

xray/forms.py
from django import forms
from .models import Xray

class XrayForm(forms.ModelForm):
    class Meta:
        model = Xray
        fields = ('image',)

book/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
import json
import pandas as pd
import numpy as np


class BookIndex(TemplateView):
    template_name = 'book/book_index.html'

def book_python(request):
    word = request.GET.get('search')
    cluster_li = {'SQL' : [0,1,2,3], '리눅스' : [0,1,2,3], '자바' : [1,2,3,7], 
                  '머신러닝':[1,2,5,6], '블록체인' : [0,2,4,5],'파이썬' : [1,2,5,6]}
    with open('./book/data/{}.json'.format(word)) as f:
        key = f.read().encode('utf-8')
        data = json.loads(key)
        
    center = pd.read_csv('./book/data/{}_CENTER.csv'.format(word))
    df = pd.DataFrame(list(data.values()), index = data.keys())

    li = []
    for i in range(8):
        
        ccc = np.array(center.iloc[i, 1:])
        sim = df.ix[ df['label'] == i , :-2].dot(ccc)
        
        li.append(sim.nlargest(7))
        
        
    group_no = cluster_li[word]
    books = {}
    for book_q in li[group_no[0]].index:
        books[book_q] = df['link'][book_q]
    
    books1 = {}
    for book_w in li[group_no[1]].index:
        books1[book_w] = df['link'][book_w]
    
    books2 = {}
    for book_e in li[group_no[2]].index:
        books2[book_e] = df['link'][book_e]
    
    books3 = {}
    for book_r in li[group_no[3]].index:
        books3[book_r] = df['link'][book_r]

    return render(request, 'book/book_index.html', {'books' : books, 'books1': books1, 
                                                    'books2' : books2, 'books3' : books3})
                                                    
            
            

deepbook/views.py
from django.views.generic import TemplateView, ListView, CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class HomePage(TemplateView):
    template_name = 'index.html'
    
class TeamPage(TemplateView):
    template_name = 'ourteam.html'
    
class ContactPage(TemplateView):
    template_name = 'contact.html'
    
class DeepPage(TemplateView):
    template_name = 'deep.html'
    
class BookPage(TemplateView):
    template_name = 'book.html'    
    
    
    
    
    
    

xray/views.py
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView
from .models import Xray
from django.urls import reverse_lazy
from .diagnosis import Model
from keras.models import load_model
import cv2

# Create your views here.
class XrayIndex(TemplateView):
    template_name = 'xray/xray_index.html'

class XrayCreate(CreateView):
    model = Xray
    fields=['image',]

class XrayList(ListView):
    model = Xray
    fields = ('image')
    success_url = reverse_lazy('xray:list')

class XrayDetail(DetailView):
    model = Xray

class XrayDelete(DeleteView):
    model = Xray
    success_url = reverse_lazy('xray:list')
    

def XrayDiagnosis(request, pk):
    img = Xray.objects.get(id = pk)
    path = '/home/ubuntu/workspace/DeepBook' + img.image.url
    re_img, per, label = Model(path)
    new_path = './xray/media/{}.jpg'.format(pk)
    new_path1 = './media/image/new_img/{}.jpg'.format(pk)
    new_path2 = '/media/image/new_img/{}.jpg'.format(pk)
    cv2.imwrite(new_path1, re_img)
    
    return render(request, 'xray/xray_diagnosis.html', {'path': new_path2, 'per' : per, 'label' :label})

book/templates/book/book_index.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %} 


<div class="item">
    <img src="{% static 'img/team/book4.png' %}" class="img-responsive" style="width:100%; height:620px;" salt=""> 
	<div class="carousel-caption" style="top:20%">
		<div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
			<!--<form class="form-inline">-->
			<!--<div class="form-group">-->
			<!--	<button type="livedemo" name="purchase" class="btn btn-primary btn-lg" required="required">Deep Go!</button>-->
			<!--</div>-->
			<div class="form-group">
				<h2 style="font-family:Roboto">Book-Clustering</h2>
				<h1 style="font-family:Roboto">Enter the search word</h1>
	    		<br>
                <!--<label style="font-size:15px" class="btn btn-primary btn-lg" for="my-file-selector">-->
                <!--    <input id="my-file-selector" type="file" style="display:none"  -->
                <!--    onchange="$('#upload-file-info').html(this.files[0].name)">-->
                <!--    이미지 선택-->
                <!--</label>-->
                <!--<div class="input-group">-->
                <!--<div class="custom-file">-->
                <!--  <input type="file" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04">-->
                <!--  <br>  -->
                <!--  <label class="custom-file-label" for="inputGroupFile04">Choose file</label>-->
                <!--</div>-->
                <!--<div class="input-group-append">-->
                <!--  <button class="btn btn-outline-secondary" type="button" id="inputGroupFileAddon04">Button</button>-->
                <!--</div>-->
                <!--<div class="input-group">-->
                <form action = "{% url 'book:booklist' %}#pricing" method = "get">
                {% csrf_token %}
                    <div class="input-group input-group-sm" style="width:50%;margin-left:25%;">
                        <input type="text" class="form-control " placeholder="검색 키워드를 입력하세요. ex)파이썬, 리눅스" name='search'>
                        <span class="input-group-btn">
	                    <button class="btn btn-secondary" type="submit" style="">찾기</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
	</div>
<div id="feature">
		<div class="container">
			<div class="row">
				<div class="text-center">
					<h3>Introduction</h3>
					<p style="font-family:Nanum Gothic;">기술 도서를 텍스트 마이닝과 군집 분석을 활용하여 분류하였습니다.<br>
					원하는 기술 관련 키워드를 입력하세요. ex) 파이썬, 리눅스, SQL... </p>
					
				</div>
			</div>
    	<div/>
    <div/>
{%if books%}
<div id="pricing">
		<div class="container">
			<br> <br> <br>
			<div class="pricing-area text-center">
                <div class="row">
                    <!--<div class="col-sm-4 plan price-one wow fadeInDown" data-wow-offset="0" data-wow-delay="0.2s">-->
                    <!--    <ul>-->
                    <!--        <li class="heading-one">-->
                    <!--            <h2>Start Up</h2>-->
                    <!--            <span>$6/Month</span>-->
                    <!--        </li>-->
                    <!--        <li>5 Gb Disk Space</li>-->
                    <!--        <li>1GB Dadicated Ram</li>-->
                    <!--        <li>10 Addon Domain</li>-->
                    <!--        <li>10 Email Account</li>-->
                    <!--        <li>24/7 Support</li>-->
                           
                    <!--    </ul>-->
                    <!--</div>-->

                    <!--<div class="col-sm-4 plan price-two wow fadeInDown" data-wow-offset="0" data-wow-delay="0.6s">-->
                    <!--    <ul>-->
                    <!--        <li class="heading-two">-->
                    <!--            <h2>Standard</h2>-->
                    <!--            <span>$12/Month</span>-->
                    <!--        </li>-->
                    <!--        <li>10 Gb Disk Space</li>-->
                    <!--        <li>2GB Dadicated Ram</li>-->
                    <!--        <li>20 Addon Domain</li>-->
                    <!--        <li>20 Email Account</li>-->
                    <!--        <li>24/7 Support</li>-->
                            
                    <!--    </ul>-->
                    <!--</div>-->

                    <!--<div class="col-sm-4 plan price-three wow fadeInDown" data-wow-offset="0" data-wow-delay="0.9s">-->
                    <!--    <img src="img/ri.png">-->
                    <!--    <ul>-->
                    <!--        <li class="heading-three">-->
                    <!--            <h2>Premium</h2>-->
                    <!--            <span>$24/Month</span>-->
                    <!--        </li>-->
                    <!--        <li>50 Gb Disk Space</li>-->
                    <!--        <li>8GB Dadicated Ram</li>-->
                    <!--        <li>Unlimited Addon Domain</li>-->
                    <!--        <li>Unlimited Email Account</li>-->
                    <!--        <li>24/7 Support</li>-->
                            
                    <!--    </ul>-->
                    <!--</div>-->
                    <div class="col-sm-6 col-md-3 plan price-one wow fadeInLeft">
                        <ul>
                            <li class="heading-one">
                                <h2>Group</h2>
                                <span>NO.1</span>
                            </li>
                            {% for key, value in books.items %}
                            <li><a href="{{ value }}" target="_blank">{{ key }}</a></li>
                            {% endfor %}
                          
                        </ul>
                    </div>

                    <div class="col-sm-6 col-md-3 plan price-two wow fadeInLeft">
                        <ul>
                            <li class="heading-two">
                                <h2>Group</h2></h2>
                                <span>NO.2</span>
                            </li>
                            {% for key, value in books1.items %}
                            <li><a href="{{ value }}" target="_blank">{{ key }}</a></li>
                            {% endfor %}
                           
                        </ul>
                    </div>

                    <div class="col-sm-6 col-md-3 plan price-three wow fadeInRight">
                         
                        <ul>
                            <li class="heading-three">
                                <h2>Group</h2>
                                <span>NO.3</span>
                            </li>
                            {% for key, value in books2.items %}
                            <li><a href="{{ value }}" target="_blank">{{ key }}</a></li>
                            {% endfor %}
                           
                        </ul>
                    </div>

                    <div class="col-sm-6 col-md-3 plan price-seven wow fadeInRight">
                        <ul>
                            <li class="heading-seven">
                                <h2>Group</h2>
                                <span>NO.4</span>
                            </li>
                            {% for key, value in books3.items %}
                            <li><a href="{{ value }}" target="_blank">{{ key }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                </div>
            </div><!--/pricing-area-->			
		</div>
	</div><!--/#pricing-->

<div class="text-center">
	<div class="copyright">
		&copy; 2018 <a target="_blank" href="http://bootstraptaste.com/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">DeepBook</a>. All Rights Reserved.
	</div>
</div>			
{%endif%}
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
    <!--static 폴더에 있는 css 적용-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet" >
	<link href="{% static 'css/animate.css' %}"  rel="stylesheet">
	<link href="{% static 'css/overwrite.css' %}"rel="stylesheet">
	<link href="{% static 'css/animate.min.css' %}" rel="stylesheet"> 
	<link href="{% static 'css/style.css' %}" rel="stylesheet"/> 
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Roboto|Ranga|Source+Sans+Pro|Nanum+Gothic" rel="stylesheet">
</head>
<body>
    
    <!--Navbar-->
    <header id="header">
        <nav class="navbar navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{%url 'home'%}">DeepBook</a>
                </div>				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><a href="{%url 'home'%}">Home</a></li>
                        <li><a href="{%url 'xray:index'%}">Deep</a></li>
                        <li><a href="{%url 'book:index'%}">Book</a></li>
                        <li><a href="{%url 'ourteam'%}">Our Team</a></li> 
                        <li><a href="{%url 'contact'%}">Contact</a></li>                        
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->		
    </header><!--/header-->	
    
    
    {%block body%}
    
    {%endblock%}
    
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>   
    
</body>
</html>  

templates/deep.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %} 

     <!--main page-->
	 <div class="slider">		
		<div id="about-slider">
			<div id="carousel-slider" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators visible-xs">
					<li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-slider" data-slide-to="1"></li>
					<li data-target="#carousel-slider" data-slide-to="2"></li>
				</ol>
				    <div class="item">
						<img src="{% static 'img/team/back.png' %}" class="img-responsive" style="vertical-align: width:700px; height:770px;" alt=""> 

						<div class="carousel-caption" style="top:38%">
							
							<div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
								<form class="form-inline">
									<!--<div class="form-group">-->
									<!--	<button type="livedemo" name="purchase" class="btn btn-primary btn-lg" required="required">Deep Go!</button>-->
									<!--</div>-->
									<div class="form-group">
                                        <label style="font-size:15px" class="btn btn-primary btn-lg" for="my-file-selector">
                                            <input id="my-file-selector" type="file" style="display:none"  
                                            onchange="$('#upload-file-info').html(this.files[0].name)">
                                            폐결절 진단
                                        </label>									
                                    </div>
									
								</form>
							</div>
						</div>
				    </div> 
				</div>
			</div> <!--/#carousel-slider-->
		</div><!--/#about-slider-->
	</div><!--/#slider-->
    </div>


{% endblock %}

templates/index.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %}
    
     <!--main page-->
	 <div class="slider">		
		<div id="about-slider">
			<div id="carousel-slider" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators visible-xs">
					<li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-slider" data-slide-to="1"></li>
					<li data-target="#carousel-slider" data-slide-to="2"></li>
				</ol>
				    <div class="item">
						<img src="{% static 'img/team/home.png' %}" class="img-responsive" style="width:100%; height:570px;" alt=""> 

						<div class="carousel-caption" style="top:30%">
							<div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.3s">								
								<h2>Our Services</h2>
							</div>
							<div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.6s">								
								<p>폐렴 진단 및 기술 도서 분류 서비스</p>
							</div>
							<div class="wow fadeInUp" data-wow-offset="0" data-wow-delay="0.9s">								
								<form class="form-inline" >
									<div class="form-group">
										<a href="{%url 'xray:index'%}" class="btn btn-primary btn-lg">Deep Go!</a>
									</div>
									<div class="form-group">
										<a href="{%url 'book:index'%}" class="btn btn-primary btn-lg">Book Go!</a>
									</div>
								</form>
							</div>
						</div>
				    </div> 
				</div>
			</div> <!--/#carousel-slider-->
		</div><!--/#about-slider-->
	</div><!--/#slider-->
    </div>
    
    <div id="feature">
		<div class="container">
			<div class="row">
				<div class="text-center">
					<h3>Introduction</h3>
					<p style="font-family:Nanum Gothic;">삼성 멀티캠퍼스  <딥러닝 기반의 빅데이터 분석 전문가> 교육에서 시작된 프로젝트로<br>
					딥러닝과 머신러닝 기반의 서비스입니다.</p>
				</div>
			</div>
    	<div/>
    <div/>
    	<div class="text-center">
		<div class="copyright">
			<br>
			&copy; 2018 <a target="_blank" href="http://bootstraptaste.com/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">DeepBook</a>. All Rights Reserved.
		</div>
	</div>	
{%endblock%}

templates/server.html
<!--사용자가 업로드하는 이미지를 보여주는 곳-->

{% extends 'base.html' %}
{% block body_block%}

    {{Deep.image}}
    {{Deep.result}}
    {{Deep.time}}
    {{Deep.user}}
    
{% endblock %}

xray/templates/xray/xray_confirm_delete.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %} 

<h1>Xray Delete</h1>

<form method="post">
    {% csrf_token %}
    <p>{{ xray.pk }}번, 삭제하시겠습니까?</p>
    <input type="submit" value="Confirm"/>
</form>

{% endblock %}

xray/templates/xray/xray_detail.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %} 

<h1>Xray Detail</h1>

<form id="myForm" action = "{% url 'xray:diagnosis' pk=xray.pk %}" method = 'post'>
    {% csrf_token %}
<div style="vertical-align:middle; text-align:center">
<br>
<br>
<br>
<br>
<br>
<br>
<img src="{% static 'img/team/zz.gif' %}" alt="">
    	<br><h2> 로딩중입니다...<h2></br>
    <!--<img src="{{ xray.image.url }}"></img>-->
    <!--<a href="#" class="btn btn-primary btn-lg">진단</a>-->
    <!--<input type = 'submit' value ='진단'>-->
</div>

<!--<a href="{% url 'xray:delete' pk=xray.pk %}">Delete</a>-->
</form>
<script src="http://code.jquery.com/jquery-1.4.4.min.js"></script>
<script>
$(document).ready(function() {
    document.getElementById("myForm").submit();
});
</script>
{% endblock %}

xray/templates/xray/xray_diagnosis.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load mathfilters %}

{% block body %}

<style>
@import url('https://fonts.googleapis.com/css?family=Do+Hyeon&subset=korean');
p {
    font-family: "Nanum Gothic", sans-serif;
    font-size: 15px;
}
p.a {
    font-weight: 400;
}
</style>

<link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

<div style="margin-top: 120px;">
  <section id="about">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 203.6" style="enable-background:new 0 0 100 203.6;" xml:space="preserve">
      <g transform="translate(0.000000,749.000000) scale(0.100000,-0.100000)">
  	  <path d="M0,6471.9V5454.2h206.5h206.5v436.2v436.2h7.6c19.8,0.3,107.9,5.7,128.3,8.2c90.2,10.9,154.9,29.4,220.4,62.8c141.1,72.6,213.3,213.3,228.3,444.1c8.7,135.3-7.3,272.3-42.9,368.3c-48.6,130.5-131,212.8-253.8,253.8c-15.5,5.2-43.5,12.8-62.2,17.1l-34,7.3l-302.2,0.8L0,7490V6471.9z M490.5,7190.8c51.1-13.6,71.2-28.8,92.9-69.8c22.3-41.9,26.4-81.5,24.7-243.2l-1.4-115l-8.4-32.1c-10.9-40.5-13.6-45.4-35.6-67.9c-21.2-22-30.7-27.4-60.6-34.5c-18.8-4.3-68.2-10.9-82.6-10.9c-3.3,0-3.8,44-3.8,291.1v291.3l26.6-1.6C456.8,7197.3,478.6,7194,490.5,7190.8z"/>
    </g>
    </svg>
  
    <div class="wrapper">
      <div class="camera"><img src="{{ path }}" alt="Camera" style="width:300px; height:300px; margin-left: 20%;">
      <p><a href = "{%url 'xray:index'%}" class="btn btn-primary btn-lg" style="margin-left: 32%;">다른 사진 진단하기</a> </p>
      </div>

      <div class="blurb">
        <h2>Your Diagnosis <strong> Result</strong></h2>
        

        {% if label == "NORMAL" %}
        <div class="width:700px;">
          
             <div class="progress" style="width: 530px;">
            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="{{per}}" aria-valuemin="0" aria-valuemax="100">{{per}}%</div>
            </div>  
          
        </div>
          <p style="font-family:Nanum Gothic;"> 딥북(DeepBook)의 분석 결과 당신의 폐는 
          <span style="color:DodgerBlue "><strong> {{per}}% </strong></span>의 확률로 <span style="color:DodgerBlue "><strong>"정상"</strong></span>입니다. 
          <br> 앞으로도 건강한 폐를 위해 폐에 좋은 마늘, 블루베리, 도라지를 자주 섭취하십시오.<br>
        다만, 본 서비스는 참고용으로만 이용하시고 정확한 진단은 가까운 병원에 방문하세요.  
          
         
        {% else %}
          <div class="height:30px;">
            <div class="progress" style="width: 530px;">
              
            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="{{per}}" aria-valuemin="0" aria-valuemax="100">{{per}}%</div>
            </div>  
        </div>
       
        <p style="font-family:Nanum Gothic;"> 딥북(DeepBook)의 분석 결과 당신의 폐는 
        <span style="color:DodgerBlue "><strong> {{per}}% </strong></span>의 확률로 <span style="color:DodgerBlue "><strong>"폐렴"</strong></span>이 의심됩니다. 
          <br> 가까운 병원에 내원하여 정확한 진단을 받아보시길 추천합니다.<br>
          다만, 본 서비스엔 오차가 있을 수 있으며 참고용으로만 사용하십시오. 
       
          <!--<br><br><br><strong>Model Spec</strong><br>Use Model : Sm94Net based CNN<br>-->
          <!-- Data Set : Pneumonia data 6000장<br>-->

        
        {% endif %} 
        
         <br><br><strong>Model Spec</strong><br>Use Model : Sm94Net based CNN<br>
           Data Set : Normal image 2000장 Pneumonia image 4000장<br>
           Validation Accuracy : 92%</p></p>
      
        <div class="social">
          <a href="https://www.facebook.com/"><i class="icon-facebook"></i></a>
          <a href="https://www.instagram.com/"><i class="icon-instagram"></i></a>
          <a href="https://twitter.com/?lang=ko"><i class="icon-twitter"></i></a>
          <a href="https://www.pinterest.co.kr/"><i class="icon-pinterest-p"></i></a>
        </div>
      </div>
    </div>
  </section>
</div>


{% endblock %}

xray/templates/xray/xray_list.html
{%extends 'base.html'%}

{% load staticfiles %}

{% block body %} 
<h1>xray List</h1>

<ul>
{% for xray in xray_list %}
    <li>
        <a href="{% url 'xray:detail' pk=xray.pk %}">
        <img src="{{ xray.image.url }}"></img>
        </a>
        <a href="{% url 'xray:delete' pk=xray.pk %}">Delete</a>

    </li>
{% endfor %}
</ul>

{%endblock%}